---
x-gameon-service:
  # ~~~ Prod env ~~~
  game: &gameon
    image: ghcr.io/spaghetti-coder/tetris:latest
  # ~~~ Dev env ~~~
  dev: &gameon-dev
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - .:/app

services:
  gameon-dev:
    <<: *gameon-dev
    # <<: *gameon
    ports:
      - "8080:8080"
    restart: unless-stopped
